### ISSUE TITLE
AICoE-CI integration

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-sre#27]
Hey @all, please think about jobs you want the AICoE CI to run on this repo, yamllinting? What else?

Cc: @durandom

**Comment by tumido** [comment]
1) Kustomization manifests are buildable
2) Resulting Kubernetes resource validation (`kubectl create --dry-run --validate` or something)
3) Kustomization files maintain the same standard:
  - Use `commonLabels` as described in https://github.com/AICoE/aicoe-cd/issues/29
  - Don't use deprecated syntax like `bases` keyword etc.
4) Markdown linting for runbooks (?)

**Comment by goern** [comment]
oh, btw, what about: https://github.com/thoth-station/thoth-application/blob/9cbd30aed172aff33ecf5f7e21e6f558493c8694/README.md#policy-based-control-of-resources

**Comment by tumido** [comment]
@goern newer worked with OPA, so.. does it use any generic testsuite, you're referring to in your README? Or do you have any Thoth specific one that we can maybe take a look at? I couldn't find any...

I like the possibility to really test the manifests a lot!

**Comment by goern** [comment]
Ja, there is https://github.com/thoth-station/thoth-application/tree/master/policy which contains the policies we want to enforce for the thoth-application. It is just testing around, I have had no deep thoughts on it...

**Comment by tumido** [comment]
I like that. That implements a good portion of my comment above. :slightly_smiling_face: :+1:

**Comment by anishasthana** [comment]
I think @tumido hit a lot of the initial ones we'd want to be covering. ++ to what has been said so far.

**Comment by durandom** [comment]
@HumairAK you looked into https://github.com/app-sre/qontract-validator before we went with argo-cd. Is this something we could do to validate a PR?

**Comment by HumairAK** [comment]
@durandom -- It's been some time, but my guess is no, as its probably coupled with their `qontract-server` and not generalized. From their description in the ReadME: 
```
This project contains the tools necessary to bundle data into the format used by qontract-server and to JSON validate it's schema.
```
Schema Validation would actually be something useful for the `aicoe-cd` repository, and I think it's worth looking into.

**Comment by HumairAK** [comment]
+1 to ensuring Kustomizations build successfully on all overlays.

**Comment by tumido** [comment]
Another cool thing would be if the bots can diff the resources (after kustomize build) from before the PR and after and check if there are new CRDs or cluster wide resources added by the PR. This way we can know if we need to tiket PSI before merging the PR or not.

**Comment by HumairAK** [comment]
+1 @tumido  --- If this can be somehow adjustable to not only CRDs but other apigroups/kinds that we can add onto some sort of a list, that would be even better.

**Comment by tumido** [comment]
And what about we can take it one step further. If such clusterwide resources are found and approved, can we automate opening of a Service Now ticket to PSI?

**Comment by goern** [comment]
Yes we can :)

We just need some coding power to help us with that... First of all I'll turn this into a card...

**Comment by tumido** [comment]
Btw, I've started using the https://github.com/Agilicus/yaml_filter suggested in https://github.com/kubernetes-sigs/kustomize/issues/821#issuecomment-467089437 and It's so easy to populate the psi ticket attachments now. :smile: 

```
kustomize build applications/argo/overlays/dh-dev-argo | yaml_filter -i CustomResourceDefinition,ClusterRole > psi_ticket.yaml
kustomize build applications/argo-events/overlays/dh-dev-argo | yaml_filter -i CustomResourceDefinition,ClusterRole >> psi_ticket.yaml
```

the `yaml_filter` is a pretty short yet clever script, can we integrate some variation of it (that may be reading the *included* and *excluded* resources from a config file instead of args?
